describe("User Journey", ()=>{
    it("A User can find a course on the home page and complete the lessons", ()=>{
        cy.visit("http://localhost:3000")
        cy.getByData("course-0").find("a").eq(3).click()
        cy.getByData("next-lesson-button").contains("Start Course").click()
        cy.location("pathname")
            .should("eq", "/testing-your-first-application")
        cy.getByData("challenge-answer-0").click()
        cy.location("pathname")
            .should("eq", "/testing-your-first-application/app-install-and-overview")
        cy.getByData("next-lesson-button").contains("Next Lesson").click()
        cy.location("pathname")
            .should("eq", "/testing-your-first-application/installing-cypress-and-writing-our-first-test")
        cy.getByData("challenge-answer-0").click()
        cy.getByData("next-lesson-button").contains("Next Lesson").click()
        cy.location("pathname")
            .should("eq", "/testing-your-first-application/setting-up-data-before-each-test")
        cy.getByData("challenge-answer-0").click()
        cy.getByData("next-lesson-button").contains("Complete Course").click()
        cy.location("pathname")
            .should("eq", "/")
        cy.getByData("email-input").type("hello@goodness")
        cy.getByData('submit-button').click()
        cy.getByData("success-message").should("exist").contains("hello@goodness")
    })
})